### ISSUE TITLE
Percentage Complete

### ISSUE THREAD

**Issue by onlymejosh** [devthenet/voyeur#1]
hi guys, 

Great idea!

Is it possible to output the % complete of a conversion. I know you can get the information from ffmpeg but not sure how the stdout part works.

**Comment by HendrikLouw** [comment]
Thank you @onlymejosh I'm not sure whether we could get a % complete of a conversion, will experiment and see what we can do. If you find a way to do it please let us know. It would be a cool feature.

**Comment by onlymejosh** [comment]
I think I've seen a solution I'll dig and have a look.

**Comment by bittersweet** [comment]
I've seen other solutions that pipe the ffmpeg output to a file, where every line is a status message that includes the progress among other things, they would just read from that file and filter the percentage complete.

**Comment by onlymejosh** [comment]
@bittersweet - Yup that was what I remembered seeing. 

Is there a way to pipe the output to object instead of a file? That would be much better on I/O

This is what I found

```
ffmpeg -y -i input.avi -vcodec xvid -acodec mp3 -ab 96 output.avi &> output.txt
```

```
def execute_ffmpeg(command)
  progress = nil
  IO.popen(command) do |pipe|
    pipe.each("r") do |line|
      if line =~ /Duration: (d{2}):(d{2}):(d{2}).(d{1})/
        duration = (($1.to_i * 60 + $2.to_i) * 60 + $3.to_i) * 10 + $4.to_i
      end
      if line =~ /time=(d+).(d+)/
        if not duration.nil? and duration != 0
          p = ($1.to_i * 10 + $2.to_i) * 100 / duration
        else
          p = 0
        end
        p = 100 if p > 100
        if progress != p
          progress = p
          print "PROGRESS: #{progress}n"
          $defout.flush
        end
      end
    end
  end
  raise MediaFormatException if $?.exitstatus != 0
end
```

http://kpumuk.info/ruby-on-rails/encoding-media-files-in-ruby-using-ffmpeg-mencoder-with-progress-tracking/

**Comment by HendrikLouw** [comment]
@onlymejosh We are using https://github.com/ahoward/open4 to get output from the command line at the moment, just need to figure out how to get the progress by calling a method on a Converter object. I'll hopefully have some time this weekend to hack on it.

**Comment by Emerson** [comment]
Planning on looking at this soon. Would be really handy in any project using this gem.

**Comment by HendrikLouw** [comment]
I've started work on a branch here https://github.com/devthenet/voyeur/tree/track_progress

You can see changes here https://github.com/devthenet/voyeur/compare/master...track_progress 

While the branch works for getting the duration of the video and the progress time, I still want to test it a little more and make sure it doesn't break anything before merging with master.

If anyone could help out with testing/making it better that would be appreciated, you will need to use your own video file to test with and change the code in examples/track_progress.rb to use that video.

**Comment by brvtl** [comment]
@HendrikLouw what is happening with this branch?

**Comment by HendrikLouw** [comment]
Feature added in https://github.com/devthenet/voyeur/tree/0.2rc1 branch. Checkout bin/voyeur.rb for example usage.
