### ISSUE TITLE
Voyeur isn't converting to mp4

### ISSUE THREAD

**Issue by skukx** [devthenet/voyeur#11]
The Error:

Voyeur::Media.new(filename: "Untitled_Screencast.ogg").convert(to: :mp4, output_filename: "test")
 => {:status=>1, :stdout=>"", :stderr=>"ffmpeg version 0.8.3-4:0.8.3-0ubuntu0.12.04.1, Copyright (c) 2000-2012 the Libav developers\n  built on Jun 12 2012 16:52:09 with gcc 4.6.3\n**\* THIS PROGRAM IS DEPRECATED **_\nThis program is only provided for compatibility and will be removed in a future release. Please use avconv instead.\nInput #0, ogg, from 'Untitled_Screencast.ogg':\n  Duration: 00:00:12.86, start: 0.000000, bitrate: 290 kb/s\n    Stream #0.0: Video: theora, yuv420p, 1366x768 [PAR 1:1 DAR 683:384], 15 tbr, 15 tbn, 15 tbc\nUnknown encoder 'libx264'\n", :error_message=>"ffmpeg version 0.8.3-4:0.8.3-0ubuntu0.12.04.1, Copyright (c) 2000-2012 the Libav developers\n  built on Jun 12 2012 16:52:09 with gcc 4.6.3\n**_ THIS PROGRAM IS DEPRECATED ***\nThis program is only provided for compatibility and will be removed in a future release. Please use avconv instead.\nInput #0, ogg, from 'Untitled_Screencast.ogg':\n  Duration: 00:00:12.86, start: 0.000000, bitrate: 290 kb/s\n    Stream #0.0: Video: theora, yuv420p, 1366x768 [PAR 1:1 DAR 683:384], 15 tbr, 15 tbn, 15 tbc\nUnknown encoder 'libx264'\n", :media=>#<Voyeur::Media:0x00000000be8020 @filename="/home/skukx/Videos/test.mp4">} 
1.9.3-p194 :007 > Voyeur::Media.new(filename: "Untitled_Screencast.ogg").convert_to_html5(output_filename: "test")
 => [:mp4, :ogv, :webm]

The only files successfully converted are ogv and webm.  Even attempting to convert just mp4 doesn't work either.

**Comment by HendrikLouw** [comment]
This seems related to the ffmpeg version that comes with Ubuntu 12.04, I'll setup a VM and test for you. 

In the meanwhile could you possibly try and install ffmpeg as follows https://github.com/devthenet/ffmpeg_setup/blob/master/ubuntu_ffmpeg_setup
