### ISSUE TITLE
no such file to load -- voyeur

### ISSUE THREAD

**Issue by dedico** [devthenet/voyeur#3]
Hi,

I wanted to try your nice gem, unfortunately I get following error when trying to run simple sample app:
### 

/home/marek/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require': 
no such file to load -- voyeur (LoadError)
from /home/marek/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
### 

I installed ffmpeg and I can convert videos using ffmpeg commands. The gem voyeur is installed too, after gem list I get:
[...]
voyeur (0.1.0)
[...]

The sample I'm trying to run is:
### 

require 'rubygems'
require 'voyeur'

Voyeur::Video.new( filename: 'test.avi' ).convert( to: :mp4 )
### 

I have no idea what can cause the problem that it can't load your gem...
Thanks,
Marek

**Comment by dedico** [comment]
I forgot to mention my system is Ubuntu 10.04.

**Comment by HendrikLouw** [comment]
@dedico thank you for reporting this bug, It's a mistake from our side, it's fixed on master and a minor version is pushed up to rubygems. 

You can install the fixed version by doing a gem install voyeur again.

It should be 0.1.1

Let us know if there's anything else.
