### ISSUE TITLE
uninitialized constant Object::Voyeur (NameError)

### ISSUE THREAD

**Issue by hello-gawjus** [devthenet/voyeur#4]
Hi,

 Love the gem. 

I get this error:

_uninitialized constant Object::Voyeur (NameError)_

on the following example code:

``` ruby
require 'rubygems' 
require 'voyeur'

Voyeur::Video.new( filename: 'test.mov' ).convert( to: :mp4 )
```

**Comment by hello-gawjus** [comment]
I resolved this issue locally by manually creating Voyeur.rb inside lib. For some reason gem install didn't pull that one down. Perhaps it saw Voyeur.rb and voyeur.rb as the same file. 

I will test this more to see if this file skipping behavior is consistent or an anomaly. I am on MacOSX Lion, by the way.

**Comment by brvtl** [comment]
I have resolved this issue. Please pull the new version and let us know if you continue to have problems.

Thanks
