### ISSUE TITLE
ffmpeg process hangs

### ISSUE THREAD

**Issue by armakan** [devthenet/voyeur#9]
Trying to use voyeur in my RoR app, with the following usage: 

```
  mp4_vid  = Voyeur::Video.new(filename: file_path).convert(to: :mp4, output_path: "#{Rails.root.to_s}/tmp/processed_videos")
  ogv_vid  = Voyeur::Video.new(filename: file_path).convert(to: :ogv, output_path: "#{Rails.root.to_s}/tmp/processed_videos")
  webm_vid = Voyeur::Video.new(filename: file_path).convert(to: :webm, output_path: "#{Rails.root.to_s}/tmp/processed_videos")
```

i also tried this way as well:

videos = Voyeur::Video.new(filename: file_path).convert_to_html5(output_path: "#{Rails.root.to_s}/tmp")

Either way, if I watch it in console, the command never finishes. Looking in Activity Monitor (this is on OSX Lion, BTW), I see ffmpeg is using 0% CPU but still hanging around. If I kill the ffmpeg process, the command completes and the video file works fine. Any ideas how to fix this? I'm willing to do it myself if I knew what was up.

**Comment by armakan** [comment]
If it helps any, I think the error is here (converter.rb):

[3] pry(#Voyeur::Mp4)> status = Open4::popen4(command) do |pid, stdin, stdout, stderr|
[3] pry(#Voyeur::Mp4)\*   out = stdout.read.strip
[3] pry(#Voyeur::Mp4)\*   err = stderr.read.strip
[3] pry(#Voyeur::Mp4)\* end  

It sits in that block until I kill the process, and then I get the below output:

=> #<Process::Status: pid 80303 SIGKILL (signal 9)>

**Comment by armakan** [comment]
Sorry for some reason it commented out the output: => #Process::Status: pid 80303 SIGKILL (signal 9)

**Comment by HendrikLouw** [comment]
Hi @armakan  

Have you tried to run ffmpeg manually to see that it works first?

Try running

 ffmpeg -i filename.avi new_filename.ogv

etc

Let us know what the output for that command is.

**Comment by valachi** [comment]
I have the same problem using delay_job.
def convert
 Voyeur::Media.new( filename: path ).convert to: :webm
end

delay.convert

ps aux | grep ffmpeg
valachi  14594 39.3  0.8  78052 18156 ?        Sl   17:52   6:24 ffmpeg -i filename.avi -b 1500k -vcodec libvpx -acodec libvorbis -ab 160000 -f webm -g 30 output_filename.webm

it just hangs there always between 6-19 - 6-25 and nothing happens. Using ffmpeg directly works just fine.

What could it be?

**Comment by HendrikLouw** [comment]
@valachi I think it might be how we handle the output from ffmpeg, I'm currently busy but I'll try to get some time to debug this, hopefully @petergarbers could also have a look.

@valachi could you please supply more information about your environment? OS, ruby version, ffmpeg version etc

**Comment by valachi** [comment]
uname -a
Linux ubuntu 3.2.0-27-generic #43-Ubuntu SMP Fri Jul 6 14:46:35 UTC 2012 i686 i686 i386 GNU/Linux

ruby -v
ruby 1.9.3p0 (2011-10-30 revision 33570) [i686-linux]
rails 3.2

ffmpeg -v
ffmpeg version git-2012-07-31-52bd9cb Copyright (c) 2000-2012 the FFmpeg developers
  built on Jul 31 2012 16:20:19 with gcc 4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5)
  configuration: --enable-gpl --enable-libfaac --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librtmp --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-version3 --enable-x11grab
  libavutil      51. 66.100 / 51. 66.100
  libavcodec     54. 46.100 / 54. 46.100
  libavformat    54. 22.100 / 54. 22.100
  libavdevice    54.  2.100 / 54.  2.100
  libavfilter     3.  5.101 /  3.  5.101
  libswscale      2.  1.100 /  2.  1.100
  libswresample   0. 15.100 /  0. 15.100
  libpostproc    52.  0.100 / 52.  0.100
Missing argument for option 'v'

I think it might be something with voyeur\delayed_job compatibility . Adding delayed_job (in addition to delayed_job_active_record) solved the problem. At least for now.

**Comment by brvtl** [comment]
Great! Thanks for letting us know. Closing this issue. Keep us posted :)
